### ISSUE TITLE
aws-lite `import` doesn't actually import DynamoDB client?

### ISSUE THREAD

**Issue by mhart** [architect/aws-lite-benchmarks#5]
In the docs for the `import / require` part of the benchmark it says:

> import / require times are tied to individual services; in this benchmark, only the DynamoDB service client is imported

But I don't that's true for aws-lite?

I might be misunderstanding something here – but it looks to me like the DynamoDB client is only imported in the `instantiate` step for aws-lite, not the `import` step?

https://github.com/architect/aws-lite-performance/blob/968a3b0b62feecaca5966a5bc5e8d4e9363619e2/src/lambdas/aws-lite-raw/index.mjs#L14

Compare with:

https://github.com/architect/aws-lite-performance/blob/968a3b0b62feecaca5966a5bc5e8d4e9363619e2/src/lambdas/aws-sdk-v3-raw/index.mjs#L9

I think it would be more true to the description (and more like-for-like) if `await import('@aws-lite/dynamodb')` was moved to the `import / require` stage.

I'd imagine overall latency wouldn't change – but as it stands, the "2x-5x faster" seems like it's not comparing the same thing? ie, in v2 and v3 all the module requiring has been completed in the import step (as you'd expect), but with aws-lite it hasn't.

Eyeballing looks like it'd only add 20ms anyway, so still should be faster than the other two (I imagine?)

**Comment by mhart** [comment]
This should fix it:

```js
  return await run({
    importDep: async () => {
      const awsClient = (await import('@aws-lite/client')).default
      await import('@aws-lite/dynamodb')
      return awsClient
    },

    instantiate: async (awsLite) => {
      return await awsLite({ plugins: [ import('@aws-lite/dynamodb') ] })
    },
    // ...
  }
```

Or if the extra `import()` call is slow for some reason (it shouldn't be 'cause of the module cache, but just in case):

```js
  let ddbPlugin

  return await run({
    importDep: async () => {
      const awsClient = (await import('@aws-lite/client')).default
      ddbPlugin = import('@aws-lite/dynamodb')
      await ddbPlugin
      return awsClient
    },

    instantiate: async (awsLite) => {
      return await awsLite({ plugins: [ ddbPlugin ] })
    },
    // ...
  }
```

**Comment by ryanblock** [comment]
Ah, yeah, that makes sense, let's definitely get this patched!
