### ISSUE TITLE
DynamoDB slowness?

### ISSUE THREAD

**Issue by mhart** [architect/aws-lite-benchmarks#7]
Hey, sorry this isn't really an issue, just a discussion/question.

Was just wondering why the DynamoDB GetItem call seems to be so slow? (ie, 120+ms)

I saw that it's a "flat 100kb record" but I wasn't sure specifically what that meant – have you got the table definition, and initial seeding code handy at all?

Not urgent in any way – it just piqued my interest is all.

**Comment by ryanblock** [comment]
All good! Here's the table seeding code: https://github.com/architect/aws-lite-performance/blob/main/bench/index.mjs#L38-L49

**Comment by mhart** [comment]
> All good! Here's the table seeding code: https://github.com/architect/aws-lite-performance/blob/main/bench/index.mjs#L38-L49

Ah, duh, dunno how I missed that – thanks mate

**Comment by mhart** [comment]
> > All good! Here's the table seeding code: https://github.com/architect/aws-lite-performance/blob/main/bench/index.mjs#L38-L49
> 
> Ah, duh, dunno how I missed that – thanks mate

(actually, that's not quite accurate, I do know how I missed it – I actually did search for the table name but only the one hit came up in the Lambda source – now I see why! Thanks again)

**Comment by mhart** [comment]
So in my limited understanding of aws-lite and its datatype conversion, this is actually putting a 133kb `S` value into `data` isn't it? Or is it a `B` value?

```js
      Item: {
        id: 'data',
        data: Buffer.alloc(hundredKB).toString('base64')
      }
```

**Comment by ryanblock** [comment]
Ah, fair point, with base64 encoding it may be greater than 100 KB; I don't think I actually checked the final string size. Should be negligible in stats but always worth being completely correct about things!

**Comment by mhart** [comment]
Yeah, not too fussed, was just trying to understand if it was being converted to binary somehow – distracted by the base64 – but I guess it's just a string in/out of DDB.
